services:

    db:
      container_name: postgres
      image: postgres:16
      environment:
        POSTGRES_PASSWORD: password123
      ports:
        - "5432:5432"
      volumes:
        - pgdata:/var/lib/postgresql/data/

volumes:
    pgdata: