# Generated by Django 5.0.6 on 2024-08-11 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='sheet name', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song', models.TextField(default='song')),
                ('singer', models.TextField(default='AKB48')),
                ('count', models.IntegerField(blank=True, null=True)),
                ('last_modify_date', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('sheet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='musics.sheet')),
            ],
            options={
                'db_table': 'music',
            },
        ),
    ]
